export const SCREEN_CODES = {
    COMMON: 'common',
    DASHBOARD: 'webDashboard',
    MASTER_DATA: 'webMasters'
};
export const ACTION_CODES = {
    LOGIN: 'login',
    DASHBOARD_USERIDS: 'getUserIds',
    DASHBOARD_USERDATA: 'getUserData',
    MEMBER_IDS: 'getMemberIds',
    MEMBER_DATA: 'getMemberData',
    MASTER_LOCATIONSDATA: 'getMasterLocations',
    MASTER_CATEGORIESDATA: 'getMasterCategories',
    HEALTH_IDS: 'getUserHealthFacilityIds',
    MODAL_HEALTH_IDS: 'getUnassignedHealthFacilityIds',
    HEALTH_DATA: 'getHealthFacilityData',
    EDUCATION_IDS: 'getUserEducationFacilityIds',
    MODAL_EDUCATION_IDS: 'getUnassignedEducationFacilityIds',
    EDUCATION_DATA: 'getEducationFacilityData',
    HOUSEHOLD_IDS: 'getUserHouseholdIds',
    MODAL_HOUSEHOLD_IDS: 'getUnassignedHouseholdIds',
    HOUSEHOLD_DATA: 'getHouseholdData',
    USER_LOCATION_IDS: 'getUserLocationIds',
    USER_LOCATION_STATS: 'getLocationStats',
    USER_STATS: 'getUserStats',
    ASSIGN_USERS: 'assignUsers',
    ASSIGN_LOC: 'assignLocations',
    ASSIGN_HH: 'assignHouseholds',
    ASSIGN_HEALTH: 'assignHealthFacilities',
    ASSIGN_ED: 'assignEducationFacilities',
    REQUEST_IDS: 'getUpdateRequestIds',
    REQUEST_DATA: 'getUpdateRequestData',
    REQUEST_APPROVAL: 'updateRequestsApprovalData',
    REMOVE_USERS: 'removeUsers',
    DIRECT_REMOVAL: 'DIRECT_REMOVAL',
    ASSIGNMENT_REMOVAL: 'ASSIGNMENT_REMOVAL',
    REMOVE_LOC: 'removeLocations',
    REMOVE_EF: 'removeEducationFacilities',
    REMOVE_HF: 'removeHealthFacilities',
    REMOVE_HH: 'removeHouseholds',
    UNASSIGNED_LOCIDS: 'getUnassignedLocationIds'
};
export const STORE_KEYS = {
    LOGIN_DATA: 'loginData',
    DASHBOARD_USERIDS: 'dashboardUserIds',
    DASHBOARD_USERDATA: 'dashboardUserData',
    MASTER_LOCATIONSDATA: 'masterlocations',
    MASTER_CATEGORIESDATA: 'masterCategories',
    PERIOD_DATA: 'periods',
    USER_STATS: 'userStats',
    MODAL_USERIDS: 'modalUserIds',
    MODAL_USERDATA: 'modalUserData',
    ASSIGN_USERS: 'assignUsers',
    REQUEST_DETAIL: 'reqDtl',
    REQUEST_APPROVAL: 'approvalData',
    REQUEST_REJECTION: 'rejData',
    USER_LOCS: 'userLoc',
    REMOVE_USER: 'removeUser',
    KEY_IDS: 'keyIds',
    USER_PARENTS: 'parentData'
};
